# Generated by Django 3.2.8 on 2021-12-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Vendor_Id', models.CharField(max_length=10)),
                ('Vendor_Name', models.CharField(max_length=100)),
                ('Vendor_Phone', models.CharField(max_length=10)),
                ('Delivery_Type', models.CharField(max_length=30)),
                ('Feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
