# Generated by Django 3.2.8 on 2021-12-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorPortal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Feedback',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
