# Generated by Django 3.2.8 on 2021-12-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorPortal', '0002_alter_vendor_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='Customers_Delivering',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='Maximum_Deliveries',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
