# Generated by Django 3.2.8 on 2021-12-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorPortal', '0003_auto_20211222_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Customers_Delivering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
