# Generated by Django 3.2.8 on 2021-12-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendorPortal', '0007_alter_vendor_customers_delivering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='Customers_Delivering',
            field=models.CharField(blank=True, default='Def', max_length=200, null=True),
        ),
    ]
