# Generated by Django 3.2.8 on 2021-12-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendorPortal', '0009_vendorlogin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorlogin',
            old_name='given_input',
            new_name='Vendor_ID',
        ),
    ]
