# Generated by Django 3.2.8 on 2021-12-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='Feedback',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Address_Type',
            field=models.CharField(choices=[('Work', 'Work'), ('Home', 'Home'), ('Other', 'Other')], default='Work', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='Plan_Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
