# Generated by Django 3.2.8 on 2021-12-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_rename_name_customer_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Plan_Type',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
