# Generated by Django 3.2.8 on 2021-12-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_plan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Plan_Type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
