# Generated by Django 3.2.8 on 2021-12-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_alter_customer_plan_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Feedback',
        ),
    ]
